In [4]:
import pandas as pd
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
dataset = fetch_ucirepo(id=350) 
  
# data (as pandas dataframes) 

X = dataset.data.features 
y = dataset.data.targets 
  
# Combine into one DataFrame
df = pd.concat([X, y], axis=1)

print(df.head())

       X1  X2  X3  X4  X5  X6  X7  X8  X9  X10  ...    X15    X16    X17  \
0   20000   2   2   1  24   2   2  -1  -1   -2  ...      0      0      0
1  120000   2   2   2  26  -1   2   0   0    0  ...   3272   3455   3261
2   90000   2   2   2  34   0   0   0   0    0  ...  14331  14948  15549
3   50000   2   2   1  37   0   0   0   0    0  ...  28314  28959  29547
4   50000   1   2   1  57  -1   0  -1   0    0  ...  20940  19146  19131

    X18    X19    X20   X21   X22   X23  Y
0     0    689      0     0     0     0  1
1     0   1000   1000  1000     0  2000  1
2  1518   1500   1000  1000  1000  5000  0
3  2000   2019   1200  1100  1069  1000  0
4  2000  36681  10000  9000   689   679  0

[5 rows x 24 columns]

In [5]:
table_desc=dataset.variables

print(table_desc)

   name     role     type      demographic                 description units  \
0    ID       ID  Integer              NaN                         NaN  None
1    X1  Feature  Integer              NaN                   LIMIT_BAL  None
2    X2  Feature  Integer              Sex                         SEX  None
3    X3  Feature  Integer  Education Level                   EDUCATION  None
4    X4  Feature  Integer   Marital Status                    MARRIAGE  None
5    X5  Feature  Integer              Age                         AGE  None
6    X6  Feature  Integer              NaN                       PAY_0  None
7    X7  Feature  Integer              NaN                       PAY_2  None
8    X8  Feature  Integer              NaN                       PAY_3  None
9    X9  Feature  Integer              NaN                       PAY_4  None
10  X10  Feature  Integer              NaN                       PAY_5  None
11  X11  Feature  Integer              NaN                       PAY_6  None
12  X12  Feature  Integer              NaN                   BILL_AMT1  None
13  X13  Feature  Integer              NaN                   BILL_AMT2  None
14  X14  Feature  Integer              NaN                   BILL_AMT3  None
15  X15  Feature  Integer              NaN                   BILL_AMT4  None
16  X16  Feature  Integer              NaN                   BILL_AMT5  None
17  X17  Feature  Integer              NaN                   BILL_AMT6  None
18  X18  Feature  Integer              NaN                    PAY_AMT1  None
19  X19  Feature  Integer              NaN                    PAY_AMT2  None
20  X20  Feature  Integer              NaN                    PAY_AMT3  None
21  X21  Feature  Integer              NaN                    PAY_AMT4  None
22  X22  Feature  Integer              NaN                    PAY_AMT5  None
23  X23  Feature  Integer              NaN                    PAY_AMT6  None
24    Y   Target   Binary              NaN  default payment next month  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no
22             no
23             no
24             no

In [14]:
df.head()
df.tail(10)
print(df.shape)
print(df.columns.tolist())
print(df.dtypes)
df.info()
df.describe()

(30000, 24)
['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'Y']
X1     int64
X2     int64
X3     int64
X4     int64
X5     int64
X6     int64
X7     int64
X8     int64
X9     int64
X10    int64
X11    int64
X12    int64
X13    int64
X14    int64
X15    int64
X16    int64
X17    int64
X18    int64
X19    int64
X20    int64
X21    int64
X22    int64
X23    int64
Y      int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      30000 non-null  int64
 1   X2      30000 non-null  int64
 2   X3      30000 non-null  int64
 3   X4      30000 non-null  int64
 4   X5      30000 non-null  int64
 5   X6      30000 non-null  int64
 6   X7      30000 non-null  int64
 7   X8      30000 non-null  int64
 8   X9      30000 non-null  int64
 9   X10     30000 non-null  int64
 10  X11     30000 non-null  int64
 11  X12     30000 non-null  int64
 12  X13     30000 non-null  int64
 13  X14     30000 non-null  int64
 14  X15     30000 non-null  int64
 15  X16     30000 non-null  int64
 16  X17     30000 non-null  int64
 17  X18     30000 non-null  int64
 18  X19     30000 non-null  int64
 19  X20     30000 non-null  int64
 20  X21     30000 non-null  int64
 21  X22     30000 non-null  int64
 22  X23     30000 non-null  int64
 23  Y       30000 non-null  int64
dtypes: int64(24)
memory usage: 5.5 MB

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,167484.322667,1.603733,1.853133,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,-0.266200,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,129747.661567,0.489129,0.790349,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,1.133187,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

In [18]:
df["X4"]
df[["X1","X5","X10"]]

           X1  X5  X10
0       20000  24   -2
1      120000  26    0
2       90000  34    0
3       50000  37    0
4       50000  57    0
...       ...  ..  ...
29995  220000  39    0
29996  150000  43    0
29997   30000  37    0
29998   80000  41    0
29999   50000  46    0

[30000 rows x 3 columns]

In [21]:
df.loc[0:5,"X4"]
df.iloc[0:5,14]

0        0
1     3272
2    14331
3    28314
4    20940
Name: X15, dtype: int64

In [23]:
df.isnull().sum()

X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
X17    0
X18    0
X19    0
X20    0
X21    0
X22    0
X23    0
Y      0
dtype: int64

In [24]:
df.isna().sum()

X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
X17    0
X18    0
X19    0
X20    0
X21    0
X22    0
X23    0
Y      0
dtype: int64

In [26]:
# -- Handling missing data --------------------------------
df.dropna()  # drop rows with any NaN

df.dropna(subset=["X6"])  # drop rows where income is NaN

df.fillna(0)  # replace NaN with 0

df["X7"] = df["X7"].fillna(df["X7"].median())

In [27]:
# -- Dropping columns -------------------------------------
df.drop(columns=["X2", "X3"], inplace=True)

In [30]:
# -- Renaming ---------------------------------------------
df.rename(columns={"X1": "LIMIT_BAL"}, inplace=True)
df.rename(columns={"LIMIT_BAL": "X1"}, inplace=True)

df.describe()

,X1,X4,X5,X6,X7,X8,X9,X10,X11,X12,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,167484.322667,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,-0.266200,-0.291100,51223.330900,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,129747.661567,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,1.133187,1.149988,73635.860576,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,10000.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,-165580.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,3558.750000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,140000.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22381.500000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,240000.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,67091.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,1000000.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,964511.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

In [42]:
# -- Value counts -----------------------------------------
df["X1"].value_counts()


# -- Sorting ----------------------------------------------
df.sort_values("X16", ascending=False)

,X1,X4,X5,X6,X7,X8,X9,X10,X11,X12,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
2197,1000000,1,47,0,0,0,-1,0,0,964511,...,891586,927171,961664,50784,50723,896040,50000,50000,50256,0
20892,550000,2,35,2,2,2,2,2,0,539092,...,572805,823540,501370,23000,23000,18000,0,18373,18159,0
28405,500000,2,28,0,0,2,0,0,0,390393,...,355531,587067,323821,26085,13566,18975,11096,35204,10121,0
8229,500000,1,42,0,0,0,0,0,0,580928,...,569034,551702,568638,25624,21898,20851,19599,26000,20000,0
13782,380000,1,49,2,0,0,0,0,0,380933,...,308948,547880,309322,14651,12238,13479,13532,12015,11525,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14548,130000,1,35,0,0,0,0,-2,-2,8010,...,-2490,-37594,-21295,1500,1012,0,0,0,80000,0
21235,150000,2,36,2,2,2,-2,-2,-2,167094,...,-46627,-46627,-46627,5068,9,0,0,0,0,1
29491,320000,2,31,1,-2,-2,-2,-2,-2,-6029,...,-50616,-53007,-94625,185,28,12,208,8,14,1
26670,70000,2,25,0,0,0,0,0,-2,60719,...,69028,-61372,79256,2500,7500,3182,25200,102000,12152,0
23326,260000,1,36,0,0,0,0,0,-1,122825,...,90857,-81334,142645,5000,6000,5020,81569,331788,10002,0

In [43]:
# -- Correlation ------------------------------------------
df.corr(numeric_only=True)

# -- Saving -----------------------------------------------
df.to_csv("cleaned.csv", index=False)